[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_token = "29iiLtNregFkwH4n4K95GrKYcGUGC3F6D5thPE2jWQQs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/valekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
